### ISSUE TITLE
Cannot restart the app with dark theme

### ISSUE THREAD

**Issue by fmtnews** [Norbert515/dynamic_theme#11]
Hi, I'm new to flutter. I'm able to save the value in sharedpreferences and call the value back but I'm not sure how to initiate the dark theme on app load. Please provide a complete code using a sample app will be great. Thanks.

**Comment by sjmcdowall** [comment]
Ahh .. .the plugin already remembers your preference etc. and if you follow the example it should just work .. did you try the example little app ??
