### ISSUE TITLE
Please upgrade Shared_preference to newest version

### ISSUE THREAD

**Issue by NewITCorp** [Norbert515/dynamic_theme#18]
Hi, 
First of all thanks so much for a great library. This saves my time quite a lot.
please upgrade this library to a newest flutter version, including its dependency especially share_preference.

Thank you

**Comment by sjmcdowall** [comment]
Agreed .. need this updated..

**Comment by Norbert515** [comment]
Hey, thanks for the PR @sjmcdowall - I just merged it and sorry for the delay, been pretty busy.
