### ISSUE TITLE
How can I use it with Switch button/checkbox 

### ISSUE THREAD

**Issue by ABINASH56** [Norbert515/dynamic_theme#29]

**Comment by ABINASH56** [comment]
I want to enable light/dark mode through switch/checkbox  instead of button ..How can I achieve this? Please help

**Comment by Khaoz-Topsy** [comment]
You could do this:
```  Checkbox(
    value: DynamicTheme.of(context).brightness == Brightness.light,
      onChanged: (bool isLight) => DynamicTheme.of(context).setBrightness(isLight? Brightness.light : Brightness.dark),
  );```
Maybe Norbert515 has a better solution 😋

**Comment by ABINASH56** [comment]
Norbert is not replying to anyone.Thank you for your help. Your answer was helpful

**Comment by Norbert515** [comment]
Sorry for my absence - @Khaoz-Topsy answer is great. 
Additionally, a PR just landed which makes toggling the brightness easier.
