### ISSUE TITLE
The getter 'brightness' was called on null

### ISSUE THREAD

**Issue by HeinKhantZaw** [Norbert515/dynamic_theme#33]
I am using this library with switch button. 
However, I always get this error.

**The getter 'brightness' was called on null.
Receiver: null
Tried calling: brightness**

How can I solve this?
P.S I am new to flutter and I still don't know what this error means. Please help me. Thanks in advanced.

**Comment by oravecz** [comment]
Did you end up resolving this? If so, can you share? I am experiencing the same problem.
