### ISSUE TITLE
Migrating to null safety

### ISSUE THREAD

**Issue by bartektartanus** [Norbert515/dynamic_theme#51]
https://dart.dev/null-safety/migration-guide

**Comment by mliitfall** [comment]
any update on this?

**Comment by marcelomfranca** [comment]
thanx for the BuildContext update ! =)

**Comment by bartektartanus** [comment]
I've prepared PR with null safety migration and update to Flutter v2. 
Current workaround:

```yaml
dynamic_theme:
    git: https://github.com/bartektartanus/dynamic_theme.git
```

**Comment by mliitfall** [comment]
Had a problem when changing theme, it does not changing theme using custom theme.
