### ISSUE TITLE
version solving failed due to low version transitiv dependecy on shared prefrence

### ISSUE THREAD

**Issue by dipak-bacancy** [Norbert515/dynamic_theme#58]
Please upgrade the shared prefrence version as it causing error in project

**Comment by SebastienBtr** [comment]
This issue is critical, the package cannot be used in a project that uses shared_preferences because of it. All it requires is to update the dependencies of the package

**Comment by 2math** [comment]
> This issue is critical, the package cannot be used in a project that uses shared_preferences because of it. All it requires is to update the dependencies of the package

does it work if you use 
```
dependency_overrides:
     shared_preferences: ^x.x.x 
```
